language: c


addons:
  apt:
    packages:
      - lcov


install:
  - gem install coveralls-lcov


before_script: 
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters


compiler:
  - gcc
  - clang


script: 
  - cd ${TRAVIS_BUILD_DIR}
  - make && ./test-minimallib


after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' 'test-minimallib*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov coverage.info

